added new content in workflow file

diff --git a/.github/workflows/AKS_Demo.yml b/.github/workflows/AKS_Demo.yml
--- a/.github/workflows/AKS_Demo.yml
+++ b/.github/workflows/AKS_Demo.yml
@@ -1,10 +1,79 @@
+# name: Create Azure AKS With Terraform
+# on:
+#   workflow_dispatch:
+
+# permissions:
+#       id-token: write
+#       contents: read
+# jobs: 
+#   AKS-Cluster-Deployment:
+#     runs-on: ubuntu-latest
+#     defaults:
+#       run:
+#         shell: bash
+#         working-directory: AKS-Demo
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v3.1.0
+
+#       - name: Print_File_Path
+#         run: |
+#           pwd
+#           ls -la
+        
+#       - name: 'Az CLI login'
+#         uses: azure/login@v1
+#         with:
+#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
+#           client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
+#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v2.0.2
+#         with:
+#           terraform_version: latest
+#           cli_config_credentials_token: ${{ secrets.TFC_TOKEN_ID }}
+
+#       - name: Terraform Init
+#         id: init
+#         run: terraform init
+      
+#       - name: Terraform Validate
+#         id: validate
+#         run: terraform validate
+
+#       - name: Terraform Plan
+#         id: plan
+#         run: terraform plan
+#         continue-on-error: true
+
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
+
+#       - name: Terraform Apply
+#         run: terraform apply -auto-approve
+
+#       - name: Terraform Output
+#         run: terraform output
+
+#       #- name: Deploy Application
+#       #  run: |
+#       #    az aks get-credentials -n "cluster-bursting-jennet" -g "rg-refined-swine"
+#       #    kubectl apply -f ./AKSApp/aks-store-quickstart.yaml
+#       #    sleep 40
+#       #    kubectl get service store-front
+#       #    rm -rf ~/.kube
+
 name: Create Azure AKS With Terraform
 on:
   workflow_dispatch:
 
 permissions:
-      id-token: write
-      contents: read
+  id-token: write
+  contents: read
+
 jobs: 
   AKS-Cluster-Deployment:
     runs-on: ubuntu-latest
@@ -16,18 +85,23 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3.1.0
 
-      - name: Print_File_Path
+      - name: Print File Path
         run: |
           pwd
           ls -la
         
-      - name: 'Az CLI login'
+      - name: Install Azure CLI
+        run: |
+          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+          az --version
+
+      - name: Az CLI Login
         uses: azure/login@v1
         with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-  
+
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2.0.2
         with:
@@ -35,32 +109,16 @@ jobs:
           cli_config_credentials_token: ${{ secrets.TFC_TOKEN_ID }}
 
       - name: Terraform Init
-        id: init
         run: terraform init
       
       - name: Terraform Validate
-        id: validate
         run: terraform validate
 
       - name: Terraform Plan
-        id: plan
         run: terraform plan
-        continue-on-error: true
-
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
 
       - name: Terraform Apply
         run: terraform apply -auto-approve
 
       - name: Terraform Output
         run: terraform output
-
-      #- name: Deploy Application
-      #  run: |
-      #    az aks get-credentials -n "cluster-bursting-jennet" -g "rg-refined-swine"
-      #    kubectl apply -f ./AKSApp/aks-store-quickstart.yaml
-      #    sleep 40
-      #    kubectl get service store-front
-      #    rm -rf ~/.kube
